[versions]
##########################################################################
# Plugins
# Check this on https://github.com/Kotlin/dokka/releases/latest/
dokka = "2.1.0"
# Check this on https://plugins.gradle.org/plugin/dev.yumi.gradle.licenser/
yumiGradleLicenser = "2.2.1"
# Check this on https://plugins.gradle.org/plugin/co.uzzu.dotenv.gradle/
dotenv = "4.0.0"
# Check this on https://github.com/GradleUp/nmcp/releases/latest/
nmcp = "1.3.0"
##########################################################################
# Java Configuration
# The Java version the JDK will be for compiling and running code.
java = "25"
# The Java version the JDK will be for running Gradle.
gradleJava = "25"
##########################################################################
# Dependencies
# Check this on https://central.sonatype.com/artifact/io.zonky.test.postgres/embedded-postgres-binaries-bom/
embeddedPostgresBinaries = "18.1.0"
# Check this on https://central.sonatype.com/artifact/org.apache.commons/commons-compress/
commonsCompress = "1.28.0"
# Check this on https://central.sonatype.com/artifact/org.flywaydb/flyway-database-postgresql/
flyway = "11.17.0"
# Check this on https://central.sonatype.com/artifact/org.junit.jupiter/junit-jupiter-api/
junit = "6.0.1"
# Check this on https://central.sonatype.com/artifact/org.liquibase/liquibase-core/
liquibase = "5.0.1"
# Check this on https://central.sonatype.com/artifact/org.postgresql/postgresql/
postgresql = "42.7.8"
# Check this on https://central.sonatype.com/artifact/org.slf4j/slf4j-api/
slf4j = "2.0.17"
# Check this on https://central.sonatype.com/artifact/org.tukaani/xz/
xz = "1.10"
##########################################################################

[libraries]
dokkaJavaPlugin = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokka" }
embeddedPostgresBinaries-windows = { group = "io.zonky.test.postgres", name = "embedded-postgres-binaries-windows-amd64", version.ref = "embeddedPostgresBinaries" }
embeddedPostgresBinaries-darwin = { group = "io.zonky.test.postgres", name = "embedded-postgres-binaries-darwin-amd64", version.ref = "embeddedPostgresBinaries" }
embeddedPostgresBinaries-linux = { group = "io.zonky.test.postgres", name = "embedded-postgres-binaries-linux-amd64", version.ref = "embeddedPostgresBinaries" }
embeddedPostgresBinaries-alpineLinux = { group = "io.zonky.test.postgres", name = "embedded-postgres-binaries-linux-amd64-alpine", version.ref = "embeddedPostgresBinaries" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
commonsCompress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
xz = { group = "org.tukaani", name = "xz", version.ref = "xz" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
flyway = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
liquibase = { group = "org.liquibase.ext", name = "liquibase-postgresql", version.ref = "liquibase" }
junit-jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
yumiGradleLicenser = { id = "dev.yumi.gradle.licenser", version.ref = "yumiGradleLicenser" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }